twig:
    default_path: '%kernel.project_dir%/templates'
    form_themes:
        - 'bootstrap_4_layout.html.twig'
        - '@FOSCKEditor/Form/ckeditor_widget.html.twig'
    paths:
        '%kernel.project_dir%/public/css': css
    date:
        format: d-m-Y
        timezone: 'Asia/Kolkata'

when@test:
    twig:
        strict_variables: true
